image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - adelphes.android-dev-ext@0.8.0:z3IVaDRzKS8IeFWrhyaPAA==
    - mpotthoff.vscode-android-webview-debug@1.1.1:TY2OLKxxIJSs2lt3TgOpjw==
    - DiemasMichiels.emulate@1.3.0:sXCoQONS3kXpSTBuMnxkyQ==